# Generated by Django 5.0.6 on 2024-06-10 19:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_user_assign_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="assign_user",
        ),
        migrations.AddField(
            model_name="user",
            name="assign_user",
            field=models.ManyToManyField(
                blank=True, null=True, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
