# Generated by Django 5.0.6 on 2024-06-11 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0008_alter_incident_details"),
    ]

    operations = [
        migrations.AddField(
            model_name="incident",
            name="update_date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
